config/routes.rb
Rails.application.routes.draw do
  get 'contact_us', to: 'contact_form#index', as: 'contact_us'

  get 'contact_form/new'
  post 'contact_form/create'
  get 'about_us', to: 'about#index', as: 'about_us'
  resources :partners
  resources :projects
  resources :ourservices
  
  get 'kashg', to: 'cpanel#index', as: 'kashg'
  resources :hero_images
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # get 'sessions/new'
  get 'signup', to: "users#new"
  resources :users
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hero_image.rb
class HeroImage < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :subject, presence: true
    validates :body, presence: true
end

app/models/ourservice.rb
class Ourservice < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    validates :Title, presence: true, length: { minimum: 5 }
    validates :description, presence: true, length: { minimum: 10 }

end

app/models/partner.rb
class Partner < ApplicationRecord
  belongs_to :user
  has_one_attached :image
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_secure_password
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    format: /\A\S+@\S+\z/

  has_many :hero_images
  has_many :ourservices
  has_many :projects
    def self.authenticate(email, password)
        user = User.find_by(email: email)
        user && user.authenticate(password)
    end

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def self.new_token
      SecureRandom.urlsafe_base64
    end

    def remember 
      self.remember_token = user.new_token
      update_attribute(:remember_digest)
    end


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @hero_images = HeroImage.all.limit(2)
  end
end

app/controllers/cpanel_controller.rb
class CpanelController < ApplicationController
  before_action :require_signin
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @hero_images = HeroImage.all
    @ourservices = Ourservice.all
    @partners = Partner.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: %i[new create]
  before_action :require_correct_user, only: %i[edit update destroy]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'Thanks for signup!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account updated successfuly!'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, alert: 'Account successfully deleted!'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to root_path, alert: 'You are not authorized!' unless current_user?(@user)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/cpanel_helper.rb
module CpanelHelper
end

app/helpers/hero_images_helper.rb
module HeroImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ourservices_helper.rb
module OurservicesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="about">
    <div class="about__header">
        <h6>We provide the best services. Need help?</h6>
        <h1>About Us</h1>
        <p>Trust, Integrity, Punctuality, Quality, to be Open, to be Kind, to be Role Model</p>
    </div>
    <div class="about__content">
       <div class="row">
           <div class="desktop-6 phone-12 tab-port-12">
                <div class="about_text">
                    <h5>We are increasing bussiness success with the technology</h5>
                        <p>KAMICH Technologies Limited is a private company headquartered in Dar es Salaam, Tanzania. The company deals with Electrical, Electronics,
                        Information Technology and Fiber Optic services. The company aims at serving individuals,
                        private corporates and government entities</p>
                        <p>We are essential to our customers by providing the best products and 
                        services to help them achieve their aspirations.</p>

                        <p>Our mission is to be one of the leading suppliers of Electrical, Electronic, Information Technology and Optic Fiber Products/services.

Enlarging the business by varying our range of products, services and field of operation.</p>

<p>We seek to survive market conditions and contribute immensely to the economic growth of the country.</p>

                </div>
           </div>
            <div class="desktop-6 phone-12 tab-port-6">
                <div class="about_images">
                    <% @hero_images.each do |hero_image| %>
                        <% images = hero_image.images.limit(2) %>
                        <% images.each do |image| %>
                            <%= image_tag image, class: "about__img" %>
                        <% end %>
                    <% end %>
                </div>
            </div>
       </div>
    </div>

</div>

app/views/cpanel/index.html.erb
<div class="dashboard">
    <h2>Hello <%= current_user.email %></h2>
    <h3>Welcome to Control Panel</h3>
    <div class="row">
        <div class="desktop-6 tab-port-12 phone-12">
            <div class="container">
                <%= link_to "Upload Hero Image", new_hero_image_path, class: "btn btn--small btn--comp" %>
                <%= link_to "Add Services", new_ourservice_path, class: "btn btn--small btn--comp" %>
                <%= link_to "Add Projects", new_project_path, class: "btn btn--small btn--comp" %>
                <%= link_to "Add Partners", new_partner_path, class: "btn btn--small btn--comp" %>
                <%= button_to "Logout", logout_path, method: :delete, class: "btn btn--border" %>
            </div>
        </div>
    </div>
</div>

app/views/home/_slider.html.erb
<div class="tab-port-12 tab-land-12 phone-12 desktop-12">
    <div data-controller="slider" class="banner">
        <div class="slider">
            <% @hero_images.each do |hero_image| %>
                <% hero_image.images.each do |image| %>
                    <%= image_tag image, class: "slider__img" %>
                <% end %>
            <% end %>
        </div>
    
        <div class="overlay">
            <div class="row">
                <div class="desktop-12 tab-land-3 tab-port-3 phone-12">
                    <div class="banner__text">
                        <h1 class="banner-heading">Best Technology company in Tanzania</h1>
                        <p>
                        The best technology company in Tanzania excels in innovation, offering cutting-edge solutions tailored to local needs. Its commitment to quality</p>
                       <div class="btn-group">
                           
                                <%= button_to "learnmore", about_us_path, method: :get, class: "btn  btn--mob" %>
                                <%= button_to "Inquire now", contact_us_path, method: :get, class: "btn btn--main  btn--mob" %>
                           
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<section class="section">
    <%= render 'slider' %>
    <div class="message">
        <h6>
        The best technology company in Tanzania excels in innovation, offering cutting-edge solutions tailored to local needs.</h6>
        <%= button_to 'Inquire Now', contact_us_path, method: :get, class:"btn btn--mob" %>
    </div>
</section>

<div class="service" id='service'>
    <h4>OUR SERVICES</h4>
    <div class="row">
    <% @ourservices.each do |service| %>
        <div class="desktop-4 tab-port-6 tab-land-6 phone-12">
        
            <div class="service__item">
            <%= link_to ourservices_path do %>
                <%= image_tag service.image, class: "service__img" %>
                <div class="service__content">
                    <h5 class="service__title">
                        <%= service.Title %>
                    </h5>
                    <p class="service__desc"><%= service.description %></p>
                </div>
            <% end %>
            </div>
        </div>
    <% end %>
    </div>
</div>

<section class="why">
    <h1 class='why__title'>Why us</h1>
    <div class="row ">
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
                <i class="fa-solid fa-screwdriver-wrench"></i>
                <div class="content">
                    <h4>WE GOT THE TOOLS</h4>
                    <p>Lorem ipsum dolor sit amet consectetur
                     adipisicing elit.
                     Repudiandae fugiat consectetur officiis
                      impedit
                     temporibus eligendi. Reprehenderit!</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-money-check-dollar"></i>
                <div class="content">
                    <h4>COMPETITIVE PRICE</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                     Repudiandae fugiat consectetur officiis impedit
                     temporibus eligendi. Reprehenderit!</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-business-time"></i>
                <div class="content">
                    <h4>MORE YEARS OF EXPERINCE</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                     Repudiandae fugiat consectetur officiis impedit
                     temporibus eligendi. Reprehenderit!</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-phone-volume"></i>
                <div class="content">
                    <h4>Great Support</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                     Repudiandae fugiat consectetur officiis impedit
                     temporibus eligendi. Reprehenderit!</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
            <i class="fa-solid fa-medal"></i>
                <div class="content">
                    <h4> Quality Meets Assurance</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                     Repudiandae fugiat consectetur officiis impedit
                     temporibus eligendi. Reprehenderit!</p>
                </div>
            </div>
        </div>
        <div class="desktop-4 tab-port-2 tab-land-2 phone-12">
            <div class="why__card">
                <i class="fa-solid fa-truck-fast"></i>
                <div class="content">
                    <h4>Fast response</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                     Repudiandae fugiat consectetur officiis impedit
                     temporibus eligendi. Reprehenderit!</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="partners">
    <h4>OUR PARTNERS</h4>
    <div class="row">
    <% @partners.each do |partner| %>
        <div class="desktop-3 tab-port-6 tab-land-6 phone-4">
            <div class="partners__item">
                <%= image_tag partner.image, class: "partners__img" %>
            </div>
        </div>
    <% end %>
    </div>
</section>